[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "npm run serve" 